// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wolong/geo/v2/geo.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_wolong_2fgeo_2fv2_2fgeo_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_wolong_2fgeo_2fv2_2fgeo_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021006 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_wolong_2fgeo_2fv2_2fgeo_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_wolong_2fgeo_2fv2_2fgeo_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_wolong_2fgeo_2fv2_2fgeo_2eproto;
namespace wolong {
namespace geo {
namespace v2 {
class AoiPosition;
struct AoiPositionDefaultTypeInternal;
extern AoiPositionDefaultTypeInternal _AoiPosition_default_instance_;
class LanePosition;
struct LanePositionDefaultTypeInternal;
extern LanePositionDefaultTypeInternal _LanePosition_default_instance_;
class LongLatPosition;
struct LongLatPositionDefaultTypeInternal;
extern LongLatPositionDefaultTypeInternal _LongLatPosition_default_instance_;
class LongLatRectArea;
struct LongLatRectAreaDefaultTypeInternal;
extern LongLatRectAreaDefaultTypeInternal _LongLatRectArea_default_instance_;
class Position;
struct PositionDefaultTypeInternal;
extern PositionDefaultTypeInternal _Position_default_instance_;
class XYPosition;
struct XYPositionDefaultTypeInternal;
extern XYPositionDefaultTypeInternal _XYPosition_default_instance_;
}  // namespace v2
}  // namespace geo
}  // namespace wolong
PROTOBUF_NAMESPACE_OPEN
template<> ::wolong::geo::v2::AoiPosition* Arena::CreateMaybeMessage<::wolong::geo::v2::AoiPosition>(Arena*);
template<> ::wolong::geo::v2::LanePosition* Arena::CreateMaybeMessage<::wolong::geo::v2::LanePosition>(Arena*);
template<> ::wolong::geo::v2::LongLatPosition* Arena::CreateMaybeMessage<::wolong::geo::v2::LongLatPosition>(Arena*);
template<> ::wolong::geo::v2::LongLatRectArea* Arena::CreateMaybeMessage<::wolong::geo::v2::LongLatRectArea>(Arena*);
template<> ::wolong::geo::v2::Position* Arena::CreateMaybeMessage<::wolong::geo::v2::Position>(Arena*);
template<> ::wolong::geo::v2::XYPosition* Arena::CreateMaybeMessage<::wolong::geo::v2::XYPosition>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace wolong {
namespace geo {
namespace v2 {

// ===================================================================

class LongLatPosition final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:wolong.geo.v2.LongLatPosition) */ {
 public:
  inline LongLatPosition() : LongLatPosition(nullptr) {}
  ~LongLatPosition() override;
  explicit PROTOBUF_CONSTEXPR LongLatPosition(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LongLatPosition(const LongLatPosition& from);
  LongLatPosition(LongLatPosition&& from) noexcept
    : LongLatPosition() {
    *this = ::std::move(from);
  }

  inline LongLatPosition& operator=(const LongLatPosition& from) {
    CopyFrom(from);
    return *this;
  }
  inline LongLatPosition& operator=(LongLatPosition&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LongLatPosition& default_instance() {
    return *internal_default_instance();
  }
  static inline const LongLatPosition* internal_default_instance() {
    return reinterpret_cast<const LongLatPosition*>(
               &_LongLatPosition_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(LongLatPosition& a, LongLatPosition& b) {
    a.Swap(&b);
  }
  inline void Swap(LongLatPosition* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LongLatPosition* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LongLatPosition* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LongLatPosition>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LongLatPosition& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const LongLatPosition& from) {
    LongLatPosition::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LongLatPosition* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "wolong.geo.v2.LongLatPosition";
  }
  protected:
  explicit LongLatPosition(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLongitudeFieldNumber = 1,
    kLatitudeFieldNumber = 2,
  };
  // double longitude = 1;
  void clear_longitude();
  double longitude() const;
  void set_longitude(double value);
  private:
  double _internal_longitude() const;
  void _internal_set_longitude(double value);
  public:

  // double latitude = 2;
  void clear_latitude();
  double latitude() const;
  void set_latitude(double value);
  private:
  double _internal_latitude() const;
  void _internal_set_latitude(double value);
  public:

  // @@protoc_insertion_point(class_scope:wolong.geo.v2.LongLatPosition)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    double longitude_;
    double latitude_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_wolong_2fgeo_2fv2_2fgeo_2eproto;
};
// -------------------------------------------------------------------

class XYPosition final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:wolong.geo.v2.XYPosition) */ {
 public:
  inline XYPosition() : XYPosition(nullptr) {}
  ~XYPosition() override;
  explicit PROTOBUF_CONSTEXPR XYPosition(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  XYPosition(const XYPosition& from);
  XYPosition(XYPosition&& from) noexcept
    : XYPosition() {
    *this = ::std::move(from);
  }

  inline XYPosition& operator=(const XYPosition& from) {
    CopyFrom(from);
    return *this;
  }
  inline XYPosition& operator=(XYPosition&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const XYPosition& default_instance() {
    return *internal_default_instance();
  }
  static inline const XYPosition* internal_default_instance() {
    return reinterpret_cast<const XYPosition*>(
               &_XYPosition_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(XYPosition& a, XYPosition& b) {
    a.Swap(&b);
  }
  inline void Swap(XYPosition* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(XYPosition* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  XYPosition* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<XYPosition>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const XYPosition& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const XYPosition& from) {
    XYPosition::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(XYPosition* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "wolong.geo.v2.XYPosition";
  }
  protected:
  explicit XYPosition(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
  };
  // double x = 1;
  void clear_x();
  double x() const;
  void set_x(double value);
  private:
  double _internal_x() const;
  void _internal_set_x(double value);
  public:

  // double y = 2;
  void clear_y();
  double y() const;
  void set_y(double value);
  private:
  double _internal_y() const;
  void _internal_set_y(double value);
  public:

  // @@protoc_insertion_point(class_scope:wolong.geo.v2.XYPosition)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    double x_;
    double y_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_wolong_2fgeo_2fv2_2fgeo_2eproto;
};
// -------------------------------------------------------------------

class LanePosition final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:wolong.geo.v2.LanePosition) */ {
 public:
  inline LanePosition() : LanePosition(nullptr) {}
  ~LanePosition() override;
  explicit PROTOBUF_CONSTEXPR LanePosition(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LanePosition(const LanePosition& from);
  LanePosition(LanePosition&& from) noexcept
    : LanePosition() {
    *this = ::std::move(from);
  }

  inline LanePosition& operator=(const LanePosition& from) {
    CopyFrom(from);
    return *this;
  }
  inline LanePosition& operator=(LanePosition&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LanePosition& default_instance() {
    return *internal_default_instance();
  }
  static inline const LanePosition* internal_default_instance() {
    return reinterpret_cast<const LanePosition*>(
               &_LanePosition_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(LanePosition& a, LanePosition& b) {
    a.Swap(&b);
  }
  inline void Swap(LanePosition* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LanePosition* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LanePosition* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LanePosition>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LanePosition& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const LanePosition& from) {
    LanePosition::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LanePosition* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "wolong.geo.v2.LanePosition";
  }
  protected:
  explicit LanePosition(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSFieldNumber = 2,
    kLaneIdFieldNumber = 1,
  };
  // double s = 2;
  void clear_s();
  double s() const;
  void set_s(double value);
  private:
  double _internal_s() const;
  void _internal_set_s(double value);
  public:

  // int32 lane_id = 1;
  void clear_lane_id();
  int32_t lane_id() const;
  void set_lane_id(int32_t value);
  private:
  int32_t _internal_lane_id() const;
  void _internal_set_lane_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:wolong.geo.v2.LanePosition)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    double s_;
    int32_t lane_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_wolong_2fgeo_2fv2_2fgeo_2eproto;
};
// -------------------------------------------------------------------

class AoiPosition final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:wolong.geo.v2.AoiPosition) */ {
 public:
  inline AoiPosition() : AoiPosition(nullptr) {}
  ~AoiPosition() override;
  explicit PROTOBUF_CONSTEXPR AoiPosition(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AoiPosition(const AoiPosition& from);
  AoiPosition(AoiPosition&& from) noexcept
    : AoiPosition() {
    *this = ::std::move(from);
  }

  inline AoiPosition& operator=(const AoiPosition& from) {
    CopyFrom(from);
    return *this;
  }
  inline AoiPosition& operator=(AoiPosition&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AoiPosition& default_instance() {
    return *internal_default_instance();
  }
  static inline const AoiPosition* internal_default_instance() {
    return reinterpret_cast<const AoiPosition*>(
               &_AoiPosition_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(AoiPosition& a, AoiPosition& b) {
    a.Swap(&b);
  }
  inline void Swap(AoiPosition* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AoiPosition* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AoiPosition* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AoiPosition>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AoiPosition& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AoiPosition& from) {
    AoiPosition::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AoiPosition* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "wolong.geo.v2.AoiPosition";
  }
  protected:
  explicit AoiPosition(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAoiIdFieldNumber = 1,
  };
  // int32 aoi_id = 1;
  void clear_aoi_id();
  int32_t aoi_id() const;
  void set_aoi_id(int32_t value);
  private:
  int32_t _internal_aoi_id() const;
  void _internal_set_aoi_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:wolong.geo.v2.AoiPosition)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t aoi_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_wolong_2fgeo_2fv2_2fgeo_2eproto;
};
// -------------------------------------------------------------------

class Position final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:wolong.geo.v2.Position) */ {
 public:
  inline Position() : Position(nullptr) {}
  ~Position() override;
  explicit PROTOBUF_CONSTEXPR Position(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Position(const Position& from);
  Position(Position&& from) noexcept
    : Position() {
    *this = ::std::move(from);
  }

  inline Position& operator=(const Position& from) {
    CopyFrom(from);
    return *this;
  }
  inline Position& operator=(Position&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Position& default_instance() {
    return *internal_default_instance();
  }
  static inline const Position* internal_default_instance() {
    return reinterpret_cast<const Position*>(
               &_Position_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(Position& a, Position& b) {
    a.Swap(&b);
  }
  inline void Swap(Position* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Position* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Position* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Position>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Position& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Position& from) {
    Position::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Position* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "wolong.geo.v2.Position";
  }
  protected:
  explicit Position(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLanePositionFieldNumber = 1,
    kAoiPositionFieldNumber = 2,
    kLonglatPositionFieldNumber = 3,
    kXyPositionFieldNumber = 4,
  };
  // optional .wolong.geo.v2.LanePosition lane_position = 1;
  bool has_lane_position() const;
  private:
  bool _internal_has_lane_position() const;
  public:
  void clear_lane_position();
  const ::wolong::geo::v2::LanePosition& lane_position() const;
  PROTOBUF_NODISCARD ::wolong::geo::v2::LanePosition* release_lane_position();
  ::wolong::geo::v2::LanePosition* mutable_lane_position();
  void set_allocated_lane_position(::wolong::geo::v2::LanePosition* lane_position);
  private:
  const ::wolong::geo::v2::LanePosition& _internal_lane_position() const;
  ::wolong::geo::v2::LanePosition* _internal_mutable_lane_position();
  public:
  void unsafe_arena_set_allocated_lane_position(
      ::wolong::geo::v2::LanePosition* lane_position);
  ::wolong::geo::v2::LanePosition* unsafe_arena_release_lane_position();

  // optional .wolong.geo.v2.AoiPosition aoi_position = 2;
  bool has_aoi_position() const;
  private:
  bool _internal_has_aoi_position() const;
  public:
  void clear_aoi_position();
  const ::wolong::geo::v2::AoiPosition& aoi_position() const;
  PROTOBUF_NODISCARD ::wolong::geo::v2::AoiPosition* release_aoi_position();
  ::wolong::geo::v2::AoiPosition* mutable_aoi_position();
  void set_allocated_aoi_position(::wolong::geo::v2::AoiPosition* aoi_position);
  private:
  const ::wolong::geo::v2::AoiPosition& _internal_aoi_position() const;
  ::wolong::geo::v2::AoiPosition* _internal_mutable_aoi_position();
  public:
  void unsafe_arena_set_allocated_aoi_position(
      ::wolong::geo::v2::AoiPosition* aoi_position);
  ::wolong::geo::v2::AoiPosition* unsafe_arena_release_aoi_position();

  // optional .wolong.geo.v2.LongLatPosition longlat_position = 3;
  bool has_longlat_position() const;
  private:
  bool _internal_has_longlat_position() const;
  public:
  void clear_longlat_position();
  const ::wolong::geo::v2::LongLatPosition& longlat_position() const;
  PROTOBUF_NODISCARD ::wolong::geo::v2::LongLatPosition* release_longlat_position();
  ::wolong::geo::v2::LongLatPosition* mutable_longlat_position();
  void set_allocated_longlat_position(::wolong::geo::v2::LongLatPosition* longlat_position);
  private:
  const ::wolong::geo::v2::LongLatPosition& _internal_longlat_position() const;
  ::wolong::geo::v2::LongLatPosition* _internal_mutable_longlat_position();
  public:
  void unsafe_arena_set_allocated_longlat_position(
      ::wolong::geo::v2::LongLatPosition* longlat_position);
  ::wolong::geo::v2::LongLatPosition* unsafe_arena_release_longlat_position();

  // optional .wolong.geo.v2.XYPosition xy_position = 4;
  bool has_xy_position() const;
  private:
  bool _internal_has_xy_position() const;
  public:
  void clear_xy_position();
  const ::wolong::geo::v2::XYPosition& xy_position() const;
  PROTOBUF_NODISCARD ::wolong::geo::v2::XYPosition* release_xy_position();
  ::wolong::geo::v2::XYPosition* mutable_xy_position();
  void set_allocated_xy_position(::wolong::geo::v2::XYPosition* xy_position);
  private:
  const ::wolong::geo::v2::XYPosition& _internal_xy_position() const;
  ::wolong::geo::v2::XYPosition* _internal_mutable_xy_position();
  public:
  void unsafe_arena_set_allocated_xy_position(
      ::wolong::geo::v2::XYPosition* xy_position);
  ::wolong::geo::v2::XYPosition* unsafe_arena_release_xy_position();

  // @@protoc_insertion_point(class_scope:wolong.geo.v2.Position)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::wolong::geo::v2::LanePosition* lane_position_;
    ::wolong::geo::v2::AoiPosition* aoi_position_;
    ::wolong::geo::v2::LongLatPosition* longlat_position_;
    ::wolong::geo::v2::XYPosition* xy_position_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_wolong_2fgeo_2fv2_2fgeo_2eproto;
};
// -------------------------------------------------------------------

class LongLatRectArea final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:wolong.geo.v2.LongLatRectArea) */ {
 public:
  inline LongLatRectArea() : LongLatRectArea(nullptr) {}
  ~LongLatRectArea() override;
  explicit PROTOBUF_CONSTEXPR LongLatRectArea(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LongLatRectArea(const LongLatRectArea& from);
  LongLatRectArea(LongLatRectArea&& from) noexcept
    : LongLatRectArea() {
    *this = ::std::move(from);
  }

  inline LongLatRectArea& operator=(const LongLatRectArea& from) {
    CopyFrom(from);
    return *this;
  }
  inline LongLatRectArea& operator=(LongLatRectArea&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LongLatRectArea& default_instance() {
    return *internal_default_instance();
  }
  static inline const LongLatRectArea* internal_default_instance() {
    return reinterpret_cast<const LongLatRectArea*>(
               &_LongLatRectArea_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(LongLatRectArea& a, LongLatRectArea& b) {
    a.Swap(&b);
  }
  inline void Swap(LongLatRectArea* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LongLatRectArea* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LongLatRectArea* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LongLatRectArea>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LongLatRectArea& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const LongLatRectArea& from) {
    LongLatRectArea::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LongLatRectArea* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "wolong.geo.v2.LongLatRectArea";
  }
  protected:
  explicit LongLatRectArea(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNeFieldNumber = 1,
    kSwFieldNumber = 2,
  };
  // .wolong.geo.v2.LongLatPosition ne = 1;
  bool has_ne() const;
  private:
  bool _internal_has_ne() const;
  public:
  void clear_ne();
  const ::wolong::geo::v2::LongLatPosition& ne() const;
  PROTOBUF_NODISCARD ::wolong::geo::v2::LongLatPosition* release_ne();
  ::wolong::geo::v2::LongLatPosition* mutable_ne();
  void set_allocated_ne(::wolong::geo::v2::LongLatPosition* ne);
  private:
  const ::wolong::geo::v2::LongLatPosition& _internal_ne() const;
  ::wolong::geo::v2::LongLatPosition* _internal_mutable_ne();
  public:
  void unsafe_arena_set_allocated_ne(
      ::wolong::geo::v2::LongLatPosition* ne);
  ::wolong::geo::v2::LongLatPosition* unsafe_arena_release_ne();

  // .wolong.geo.v2.LongLatPosition sw = 2;
  bool has_sw() const;
  private:
  bool _internal_has_sw() const;
  public:
  void clear_sw();
  const ::wolong::geo::v2::LongLatPosition& sw() const;
  PROTOBUF_NODISCARD ::wolong::geo::v2::LongLatPosition* release_sw();
  ::wolong::geo::v2::LongLatPosition* mutable_sw();
  void set_allocated_sw(::wolong::geo::v2::LongLatPosition* sw);
  private:
  const ::wolong::geo::v2::LongLatPosition& _internal_sw() const;
  ::wolong::geo::v2::LongLatPosition* _internal_mutable_sw();
  public:
  void unsafe_arena_set_allocated_sw(
      ::wolong::geo::v2::LongLatPosition* sw);
  ::wolong::geo::v2::LongLatPosition* unsafe_arena_release_sw();

  // @@protoc_insertion_point(class_scope:wolong.geo.v2.LongLatRectArea)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::wolong::geo::v2::LongLatPosition* ne_;
    ::wolong::geo::v2::LongLatPosition* sw_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_wolong_2fgeo_2fv2_2fgeo_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LongLatPosition

// double longitude = 1;
inline void LongLatPosition::clear_longitude() {
  _impl_.longitude_ = 0;
}
inline double LongLatPosition::_internal_longitude() const {
  return _impl_.longitude_;
}
inline double LongLatPosition::longitude() const {
  // @@protoc_insertion_point(field_get:wolong.geo.v2.LongLatPosition.longitude)
  return _internal_longitude();
}
inline void LongLatPosition::_internal_set_longitude(double value) {
  
  _impl_.longitude_ = value;
}
inline void LongLatPosition::set_longitude(double value) {
  _internal_set_longitude(value);
  // @@protoc_insertion_point(field_set:wolong.geo.v2.LongLatPosition.longitude)
}

// double latitude = 2;
inline void LongLatPosition::clear_latitude() {
  _impl_.latitude_ = 0;
}
inline double LongLatPosition::_internal_latitude() const {
  return _impl_.latitude_;
}
inline double LongLatPosition::latitude() const {
  // @@protoc_insertion_point(field_get:wolong.geo.v2.LongLatPosition.latitude)
  return _internal_latitude();
}
inline void LongLatPosition::_internal_set_latitude(double value) {
  
  _impl_.latitude_ = value;
}
inline void LongLatPosition::set_latitude(double value) {
  _internal_set_latitude(value);
  // @@protoc_insertion_point(field_set:wolong.geo.v2.LongLatPosition.latitude)
}

// -------------------------------------------------------------------

// XYPosition

// double x = 1;
inline void XYPosition::clear_x() {
  _impl_.x_ = 0;
}
inline double XYPosition::_internal_x() const {
  return _impl_.x_;
}
inline double XYPosition::x() const {
  // @@protoc_insertion_point(field_get:wolong.geo.v2.XYPosition.x)
  return _internal_x();
}
inline void XYPosition::_internal_set_x(double value) {
  
  _impl_.x_ = value;
}
inline void XYPosition::set_x(double value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:wolong.geo.v2.XYPosition.x)
}

// double y = 2;
inline void XYPosition::clear_y() {
  _impl_.y_ = 0;
}
inline double XYPosition::_internal_y() const {
  return _impl_.y_;
}
inline double XYPosition::y() const {
  // @@protoc_insertion_point(field_get:wolong.geo.v2.XYPosition.y)
  return _internal_y();
}
inline void XYPosition::_internal_set_y(double value) {
  
  _impl_.y_ = value;
}
inline void XYPosition::set_y(double value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:wolong.geo.v2.XYPosition.y)
}

// -------------------------------------------------------------------

// LanePosition

// int32 lane_id = 1;
inline void LanePosition::clear_lane_id() {
  _impl_.lane_id_ = 0;
}
inline int32_t LanePosition::_internal_lane_id() const {
  return _impl_.lane_id_;
}
inline int32_t LanePosition::lane_id() const {
  // @@protoc_insertion_point(field_get:wolong.geo.v2.LanePosition.lane_id)
  return _internal_lane_id();
}
inline void LanePosition::_internal_set_lane_id(int32_t value) {
  
  _impl_.lane_id_ = value;
}
inline void LanePosition::set_lane_id(int32_t value) {
  _internal_set_lane_id(value);
  // @@protoc_insertion_point(field_set:wolong.geo.v2.LanePosition.lane_id)
}

// double s = 2;
inline void LanePosition::clear_s() {
  _impl_.s_ = 0;
}
inline double LanePosition::_internal_s() const {
  return _impl_.s_;
}
inline double LanePosition::s() const {
  // @@protoc_insertion_point(field_get:wolong.geo.v2.LanePosition.s)
  return _internal_s();
}
inline void LanePosition::_internal_set_s(double value) {
  
  _impl_.s_ = value;
}
inline void LanePosition::set_s(double value) {
  _internal_set_s(value);
  // @@protoc_insertion_point(field_set:wolong.geo.v2.LanePosition.s)
}

// -------------------------------------------------------------------

// AoiPosition

// int32 aoi_id = 1;
inline void AoiPosition::clear_aoi_id() {
  _impl_.aoi_id_ = 0;
}
inline int32_t AoiPosition::_internal_aoi_id() const {
  return _impl_.aoi_id_;
}
inline int32_t AoiPosition::aoi_id() const {
  // @@protoc_insertion_point(field_get:wolong.geo.v2.AoiPosition.aoi_id)
  return _internal_aoi_id();
}
inline void AoiPosition::_internal_set_aoi_id(int32_t value) {
  
  _impl_.aoi_id_ = value;
}
inline void AoiPosition::set_aoi_id(int32_t value) {
  _internal_set_aoi_id(value);
  // @@protoc_insertion_point(field_set:wolong.geo.v2.AoiPosition.aoi_id)
}

// -------------------------------------------------------------------

// Position

// optional .wolong.geo.v2.LanePosition lane_position = 1;
inline bool Position::_internal_has_lane_position() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.lane_position_ != nullptr);
  return value;
}
inline bool Position::has_lane_position() const {
  return _internal_has_lane_position();
}
inline void Position::clear_lane_position() {
  if (_impl_.lane_position_ != nullptr) _impl_.lane_position_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::wolong::geo::v2::LanePosition& Position::_internal_lane_position() const {
  const ::wolong::geo::v2::LanePosition* p = _impl_.lane_position_;
  return p != nullptr ? *p : reinterpret_cast<const ::wolong::geo::v2::LanePosition&>(
      ::wolong::geo::v2::_LanePosition_default_instance_);
}
inline const ::wolong::geo::v2::LanePosition& Position::lane_position() const {
  // @@protoc_insertion_point(field_get:wolong.geo.v2.Position.lane_position)
  return _internal_lane_position();
}
inline void Position::unsafe_arena_set_allocated_lane_position(
    ::wolong::geo::v2::LanePosition* lane_position) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.lane_position_);
  }
  _impl_.lane_position_ = lane_position;
  if (lane_position) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:wolong.geo.v2.Position.lane_position)
}
inline ::wolong::geo::v2::LanePosition* Position::release_lane_position() {
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::wolong::geo::v2::LanePosition* temp = _impl_.lane_position_;
  _impl_.lane_position_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::wolong::geo::v2::LanePosition* Position::unsafe_arena_release_lane_position() {
  // @@protoc_insertion_point(field_release:wolong.geo.v2.Position.lane_position)
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::wolong::geo::v2::LanePosition* temp = _impl_.lane_position_;
  _impl_.lane_position_ = nullptr;
  return temp;
}
inline ::wolong::geo::v2::LanePosition* Position::_internal_mutable_lane_position() {
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.lane_position_ == nullptr) {
    auto* p = CreateMaybeMessage<::wolong::geo::v2::LanePosition>(GetArenaForAllocation());
    _impl_.lane_position_ = p;
  }
  return _impl_.lane_position_;
}
inline ::wolong::geo::v2::LanePosition* Position::mutable_lane_position() {
  ::wolong::geo::v2::LanePosition* _msg = _internal_mutable_lane_position();
  // @@protoc_insertion_point(field_mutable:wolong.geo.v2.Position.lane_position)
  return _msg;
}
inline void Position::set_allocated_lane_position(::wolong::geo::v2::LanePosition* lane_position) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.lane_position_;
  }
  if (lane_position) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(lane_position);
    if (message_arena != submessage_arena) {
      lane_position = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, lane_position, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.lane_position_ = lane_position;
  // @@protoc_insertion_point(field_set_allocated:wolong.geo.v2.Position.lane_position)
}

// optional .wolong.geo.v2.AoiPosition aoi_position = 2;
inline bool Position::_internal_has_aoi_position() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.aoi_position_ != nullptr);
  return value;
}
inline bool Position::has_aoi_position() const {
  return _internal_has_aoi_position();
}
inline void Position::clear_aoi_position() {
  if (_impl_.aoi_position_ != nullptr) _impl_.aoi_position_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::wolong::geo::v2::AoiPosition& Position::_internal_aoi_position() const {
  const ::wolong::geo::v2::AoiPosition* p = _impl_.aoi_position_;
  return p != nullptr ? *p : reinterpret_cast<const ::wolong::geo::v2::AoiPosition&>(
      ::wolong::geo::v2::_AoiPosition_default_instance_);
}
inline const ::wolong::geo::v2::AoiPosition& Position::aoi_position() const {
  // @@protoc_insertion_point(field_get:wolong.geo.v2.Position.aoi_position)
  return _internal_aoi_position();
}
inline void Position::unsafe_arena_set_allocated_aoi_position(
    ::wolong::geo::v2::AoiPosition* aoi_position) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.aoi_position_);
  }
  _impl_.aoi_position_ = aoi_position;
  if (aoi_position) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:wolong.geo.v2.Position.aoi_position)
}
inline ::wolong::geo::v2::AoiPosition* Position::release_aoi_position() {
  _impl_._has_bits_[0] &= ~0x00000002u;
  ::wolong::geo::v2::AoiPosition* temp = _impl_.aoi_position_;
  _impl_.aoi_position_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::wolong::geo::v2::AoiPosition* Position::unsafe_arena_release_aoi_position() {
  // @@protoc_insertion_point(field_release:wolong.geo.v2.Position.aoi_position)
  _impl_._has_bits_[0] &= ~0x00000002u;
  ::wolong::geo::v2::AoiPosition* temp = _impl_.aoi_position_;
  _impl_.aoi_position_ = nullptr;
  return temp;
}
inline ::wolong::geo::v2::AoiPosition* Position::_internal_mutable_aoi_position() {
  _impl_._has_bits_[0] |= 0x00000002u;
  if (_impl_.aoi_position_ == nullptr) {
    auto* p = CreateMaybeMessage<::wolong::geo::v2::AoiPosition>(GetArenaForAllocation());
    _impl_.aoi_position_ = p;
  }
  return _impl_.aoi_position_;
}
inline ::wolong::geo::v2::AoiPosition* Position::mutable_aoi_position() {
  ::wolong::geo::v2::AoiPosition* _msg = _internal_mutable_aoi_position();
  // @@protoc_insertion_point(field_mutable:wolong.geo.v2.Position.aoi_position)
  return _msg;
}
inline void Position::set_allocated_aoi_position(::wolong::geo::v2::AoiPosition* aoi_position) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.aoi_position_;
  }
  if (aoi_position) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(aoi_position);
    if (message_arena != submessage_arena) {
      aoi_position = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, aoi_position, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.aoi_position_ = aoi_position;
  // @@protoc_insertion_point(field_set_allocated:wolong.geo.v2.Position.aoi_position)
}

// optional .wolong.geo.v2.LongLatPosition longlat_position = 3;
inline bool Position::_internal_has_longlat_position() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.longlat_position_ != nullptr);
  return value;
}
inline bool Position::has_longlat_position() const {
  return _internal_has_longlat_position();
}
inline void Position::clear_longlat_position() {
  if (_impl_.longlat_position_ != nullptr) _impl_.longlat_position_->Clear();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const ::wolong::geo::v2::LongLatPosition& Position::_internal_longlat_position() const {
  const ::wolong::geo::v2::LongLatPosition* p = _impl_.longlat_position_;
  return p != nullptr ? *p : reinterpret_cast<const ::wolong::geo::v2::LongLatPosition&>(
      ::wolong::geo::v2::_LongLatPosition_default_instance_);
}
inline const ::wolong::geo::v2::LongLatPosition& Position::longlat_position() const {
  // @@protoc_insertion_point(field_get:wolong.geo.v2.Position.longlat_position)
  return _internal_longlat_position();
}
inline void Position::unsafe_arena_set_allocated_longlat_position(
    ::wolong::geo::v2::LongLatPosition* longlat_position) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.longlat_position_);
  }
  _impl_.longlat_position_ = longlat_position;
  if (longlat_position) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:wolong.geo.v2.Position.longlat_position)
}
inline ::wolong::geo::v2::LongLatPosition* Position::release_longlat_position() {
  _impl_._has_bits_[0] &= ~0x00000004u;
  ::wolong::geo::v2::LongLatPosition* temp = _impl_.longlat_position_;
  _impl_.longlat_position_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::wolong::geo::v2::LongLatPosition* Position::unsafe_arena_release_longlat_position() {
  // @@protoc_insertion_point(field_release:wolong.geo.v2.Position.longlat_position)
  _impl_._has_bits_[0] &= ~0x00000004u;
  ::wolong::geo::v2::LongLatPosition* temp = _impl_.longlat_position_;
  _impl_.longlat_position_ = nullptr;
  return temp;
}
inline ::wolong::geo::v2::LongLatPosition* Position::_internal_mutable_longlat_position() {
  _impl_._has_bits_[0] |= 0x00000004u;
  if (_impl_.longlat_position_ == nullptr) {
    auto* p = CreateMaybeMessage<::wolong::geo::v2::LongLatPosition>(GetArenaForAllocation());
    _impl_.longlat_position_ = p;
  }
  return _impl_.longlat_position_;
}
inline ::wolong::geo::v2::LongLatPosition* Position::mutable_longlat_position() {
  ::wolong::geo::v2::LongLatPosition* _msg = _internal_mutable_longlat_position();
  // @@protoc_insertion_point(field_mutable:wolong.geo.v2.Position.longlat_position)
  return _msg;
}
inline void Position::set_allocated_longlat_position(::wolong::geo::v2::LongLatPosition* longlat_position) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.longlat_position_;
  }
  if (longlat_position) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(longlat_position);
    if (message_arena != submessage_arena) {
      longlat_position = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, longlat_position, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.longlat_position_ = longlat_position;
  // @@protoc_insertion_point(field_set_allocated:wolong.geo.v2.Position.longlat_position)
}

// optional .wolong.geo.v2.XYPosition xy_position = 4;
inline bool Position::_internal_has_xy_position() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.xy_position_ != nullptr);
  return value;
}
inline bool Position::has_xy_position() const {
  return _internal_has_xy_position();
}
inline void Position::clear_xy_position() {
  if (_impl_.xy_position_ != nullptr) _impl_.xy_position_->Clear();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline const ::wolong::geo::v2::XYPosition& Position::_internal_xy_position() const {
  const ::wolong::geo::v2::XYPosition* p = _impl_.xy_position_;
  return p != nullptr ? *p : reinterpret_cast<const ::wolong::geo::v2::XYPosition&>(
      ::wolong::geo::v2::_XYPosition_default_instance_);
}
inline const ::wolong::geo::v2::XYPosition& Position::xy_position() const {
  // @@protoc_insertion_point(field_get:wolong.geo.v2.Position.xy_position)
  return _internal_xy_position();
}
inline void Position::unsafe_arena_set_allocated_xy_position(
    ::wolong::geo::v2::XYPosition* xy_position) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.xy_position_);
  }
  _impl_.xy_position_ = xy_position;
  if (xy_position) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:wolong.geo.v2.Position.xy_position)
}
inline ::wolong::geo::v2::XYPosition* Position::release_xy_position() {
  _impl_._has_bits_[0] &= ~0x00000008u;
  ::wolong::geo::v2::XYPosition* temp = _impl_.xy_position_;
  _impl_.xy_position_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::wolong::geo::v2::XYPosition* Position::unsafe_arena_release_xy_position() {
  // @@protoc_insertion_point(field_release:wolong.geo.v2.Position.xy_position)
  _impl_._has_bits_[0] &= ~0x00000008u;
  ::wolong::geo::v2::XYPosition* temp = _impl_.xy_position_;
  _impl_.xy_position_ = nullptr;
  return temp;
}
inline ::wolong::geo::v2::XYPosition* Position::_internal_mutable_xy_position() {
  _impl_._has_bits_[0] |= 0x00000008u;
  if (_impl_.xy_position_ == nullptr) {
    auto* p = CreateMaybeMessage<::wolong::geo::v2::XYPosition>(GetArenaForAllocation());
    _impl_.xy_position_ = p;
  }
  return _impl_.xy_position_;
}
inline ::wolong::geo::v2::XYPosition* Position::mutable_xy_position() {
  ::wolong::geo::v2::XYPosition* _msg = _internal_mutable_xy_position();
  // @@protoc_insertion_point(field_mutable:wolong.geo.v2.Position.xy_position)
  return _msg;
}
inline void Position::set_allocated_xy_position(::wolong::geo::v2::XYPosition* xy_position) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.xy_position_;
  }
  if (xy_position) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(xy_position);
    if (message_arena != submessage_arena) {
      xy_position = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, xy_position, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  _impl_.xy_position_ = xy_position;
  // @@protoc_insertion_point(field_set_allocated:wolong.geo.v2.Position.xy_position)
}

// -------------------------------------------------------------------

// LongLatRectArea

// .wolong.geo.v2.LongLatPosition ne = 1;
inline bool LongLatRectArea::_internal_has_ne() const {
  return this != internal_default_instance() && _impl_.ne_ != nullptr;
}
inline bool LongLatRectArea::has_ne() const {
  return _internal_has_ne();
}
inline void LongLatRectArea::clear_ne() {
  if (GetArenaForAllocation() == nullptr && _impl_.ne_ != nullptr) {
    delete _impl_.ne_;
  }
  _impl_.ne_ = nullptr;
}
inline const ::wolong::geo::v2::LongLatPosition& LongLatRectArea::_internal_ne() const {
  const ::wolong::geo::v2::LongLatPosition* p = _impl_.ne_;
  return p != nullptr ? *p : reinterpret_cast<const ::wolong::geo::v2::LongLatPosition&>(
      ::wolong::geo::v2::_LongLatPosition_default_instance_);
}
inline const ::wolong::geo::v2::LongLatPosition& LongLatRectArea::ne() const {
  // @@protoc_insertion_point(field_get:wolong.geo.v2.LongLatRectArea.ne)
  return _internal_ne();
}
inline void LongLatRectArea::unsafe_arena_set_allocated_ne(
    ::wolong::geo::v2::LongLatPosition* ne) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.ne_);
  }
  _impl_.ne_ = ne;
  if (ne) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:wolong.geo.v2.LongLatRectArea.ne)
}
inline ::wolong::geo::v2::LongLatPosition* LongLatRectArea::release_ne() {
  
  ::wolong::geo::v2::LongLatPosition* temp = _impl_.ne_;
  _impl_.ne_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::wolong::geo::v2::LongLatPosition* LongLatRectArea::unsafe_arena_release_ne() {
  // @@protoc_insertion_point(field_release:wolong.geo.v2.LongLatRectArea.ne)
  
  ::wolong::geo::v2::LongLatPosition* temp = _impl_.ne_;
  _impl_.ne_ = nullptr;
  return temp;
}
inline ::wolong::geo::v2::LongLatPosition* LongLatRectArea::_internal_mutable_ne() {
  
  if (_impl_.ne_ == nullptr) {
    auto* p = CreateMaybeMessage<::wolong::geo::v2::LongLatPosition>(GetArenaForAllocation());
    _impl_.ne_ = p;
  }
  return _impl_.ne_;
}
inline ::wolong::geo::v2::LongLatPosition* LongLatRectArea::mutable_ne() {
  ::wolong::geo::v2::LongLatPosition* _msg = _internal_mutable_ne();
  // @@protoc_insertion_point(field_mutable:wolong.geo.v2.LongLatRectArea.ne)
  return _msg;
}
inline void LongLatRectArea::set_allocated_ne(::wolong::geo::v2::LongLatPosition* ne) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.ne_;
  }
  if (ne) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(ne);
    if (message_arena != submessage_arena) {
      ne = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, ne, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.ne_ = ne;
  // @@protoc_insertion_point(field_set_allocated:wolong.geo.v2.LongLatRectArea.ne)
}

// .wolong.geo.v2.LongLatPosition sw = 2;
inline bool LongLatRectArea::_internal_has_sw() const {
  return this != internal_default_instance() && _impl_.sw_ != nullptr;
}
inline bool LongLatRectArea::has_sw() const {
  return _internal_has_sw();
}
inline void LongLatRectArea::clear_sw() {
  if (GetArenaForAllocation() == nullptr && _impl_.sw_ != nullptr) {
    delete _impl_.sw_;
  }
  _impl_.sw_ = nullptr;
}
inline const ::wolong::geo::v2::LongLatPosition& LongLatRectArea::_internal_sw() const {
  const ::wolong::geo::v2::LongLatPosition* p = _impl_.sw_;
  return p != nullptr ? *p : reinterpret_cast<const ::wolong::geo::v2::LongLatPosition&>(
      ::wolong::geo::v2::_LongLatPosition_default_instance_);
}
inline const ::wolong::geo::v2::LongLatPosition& LongLatRectArea::sw() const {
  // @@protoc_insertion_point(field_get:wolong.geo.v2.LongLatRectArea.sw)
  return _internal_sw();
}
inline void LongLatRectArea::unsafe_arena_set_allocated_sw(
    ::wolong::geo::v2::LongLatPosition* sw) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.sw_);
  }
  _impl_.sw_ = sw;
  if (sw) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:wolong.geo.v2.LongLatRectArea.sw)
}
inline ::wolong::geo::v2::LongLatPosition* LongLatRectArea::release_sw() {
  
  ::wolong::geo::v2::LongLatPosition* temp = _impl_.sw_;
  _impl_.sw_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::wolong::geo::v2::LongLatPosition* LongLatRectArea::unsafe_arena_release_sw() {
  // @@protoc_insertion_point(field_release:wolong.geo.v2.LongLatRectArea.sw)
  
  ::wolong::geo::v2::LongLatPosition* temp = _impl_.sw_;
  _impl_.sw_ = nullptr;
  return temp;
}
inline ::wolong::geo::v2::LongLatPosition* LongLatRectArea::_internal_mutable_sw() {
  
  if (_impl_.sw_ == nullptr) {
    auto* p = CreateMaybeMessage<::wolong::geo::v2::LongLatPosition>(GetArenaForAllocation());
    _impl_.sw_ = p;
  }
  return _impl_.sw_;
}
inline ::wolong::geo::v2::LongLatPosition* LongLatRectArea::mutable_sw() {
  ::wolong::geo::v2::LongLatPosition* _msg = _internal_mutable_sw();
  // @@protoc_insertion_point(field_mutable:wolong.geo.v2.LongLatRectArea.sw)
  return _msg;
}
inline void LongLatRectArea::set_allocated_sw(::wolong::geo::v2::LongLatPosition* sw) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.sw_;
  }
  if (sw) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(sw);
    if (message_arena != submessage_arena) {
      sw = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, sw, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.sw_ = sw;
  // @@protoc_insertion_point(field_set_allocated:wolong.geo.v2.LongLatRectArea.sw)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace v2
}  // namespace geo
}  // namespace wolong

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_wolong_2fgeo_2fv2_2fgeo_2eproto
